orbs:
  inspecode:
    executors:
      default:
        docker:
          - image: python:3
    commands:
      run_job:
        description: Run a new inspecode job.
        parameters:
          api_token:
            description: Your API token to access the Inspecode API.
            type: string
            default: "${INSPECODE_API_TOKEN}"
          service:
            description: Your VCS provider.
            type: enum
            enum: ["github", "bitbucket"]
            default: "github"
          account_name:
            description: Your user or organization name.
            type: string
            default: "${CIRCLE_PROJECT_USERNAME}"
          repo_name:
            description: Your repository name.
            type: string
            default: "${CIRCLE_PROJECT_REPONAME}"
          branch_name:
            description: The branch name.
            type: string
            default: "${CIRCLE_BRANCH}"
          commit_sha:
            description: The SHA-1 of the commit.
            type: string
            default: "${CIRCLE_SHA1}"
        steps:
          - run:
              name: Choose the domain name of the vcs provider.
              command: |
                if [ << parameters.service >> = "github" ]; then
                  INSPECODE_API_SERVICE_URL="github.com"
                else
                  INSPECODE_API_SERVICE_URL="bitbucket.org"
                fi
          - run:
              name: Build the url of the API.
              command: |
                INSPECODE_API_URL="https://inspecode.rocro.com/api/1/jobs/${INSPECODE_API_SERVICE_URL}/<< parameters.account_name >>/<< parameters.repo_name >>"
          - run:
              name: Build the request body.
              command: |
                INSPECODE_API_REQUEST_BODY="{\"branch\":\"<< parameters.branch_name >>\", \"commit\":\"<< parameters.commit_sha >>\"}"
          - run:
              name: Send the request.
              command: |
                INSPECODE_API_RESPONSE_BODY="$(curl --request POST --retry 3 --fail -H "X-API-Key: << parameters.api_token >>" \
                  --data "${INSPECODE_API_REQUEST_BODY}" "${INSPECODE_API_URL}")"
          - run:
              name: Parse the response.
              command: |
                INSPECODE_API_JOB_ID="$(echo "${INSPECODE_API_RESPONSE_BODY}" | python3 -c "import sys, json; print(json.load(sys.stdin)['jobID'])")"
      wait_job:
    jobs:
      run:
        executor: default
        steps:
          - run_job

version: 2.1
workflows:
  main:
    jobs:
      - inspecode/run
