orbs:
  my-orb:
    executors:
      default:
        docker:
          - image: circleci/node
    commands:
      printEnvs:
        steps:
          - run: echo "${CIRCLE_REPOSITORY_URL}"
          - run: echo "${CIRCLE_PROJECT_USERNAME}"
          - run: echo "${CIRCLE_PROJECT_REPONAME}"
          - run: echo "${CIRCLE_SHA1}"
          - run: echo "${CIRCLE_BRANCH}"
      letItFail:
        steps:
          - run: false
    jobs:
      myjob:
        executor: default
        steps:
          - printEnvs
          - letItFail
version: 2.1
workflows:
  main:
    jobs:
      - my-orb/myjob
